#!/bin/bash
cat << EOF
usage: up [--level <n>| -n <levels>][--help][--version]
:::::::::::cccccccccccccccccccccccccccccccclllllccccccccllllcccccccccccccccccccclllllllcccccccc::::;;;;:ccccc:::ccloodxxkkxxxxkkkkkkkkkkkkOOOOOO000000
:::::::::::::cccccccccccccccccccccccccccccclllcccccccccllllllcccccccccccccccccccclcccccccc::::;;;;;;;;;;:::ccccclllooodxxkkkxxkkkkkkkkkkkkOOOOOO000000
:::::::::::::::ccccccccccccccccccccccccccccccccccccccclllllllllccccccccccccccccccc::::;;;;;;,,,,,,,,;::::::::ccclloooooddxxkkkkkkkkOOOkkkkOOOO00000000
:::::::::::::::cccccccccccccccccccccccccccccccccccccccllllllllcccccccccccc::::;;;,,,,,,,,,,,''''''',,;;;::::::ccloodddddxxxkkkkkkkkOOOOOkOOOO000000000
::::::::::::ccccccccccccccccccccccccccccccccccccccccccllllllllcccccccccc::;;;,,,,,,',,,,,,''''',,,,,,,;;::ccclllooddxxxxkkkkkkkkkkOOOOOOOOO00000000000
::::::::::ccccccccccccccclllllllccccccccccccccccccccclllllllllccccccccc::;;;;,,;;;;,,;;;;;,,,,;;;:::::cccllooodddxxxkkkkkkkOOOOOOOOOOOOOOOO00000000000
;:::::::::cccccccccccccccccllllllccccccccccccccccccccclllllllccccc::::::::::;;;;:::;;::::::::::::ccccclllloodddxxxkkkkOOOOOOOOOOOOOOOOOOOOOOOO00000000
;;;;;;;;;;:::::::::::::::::cccccccccllllllcccccccccccclllllllccccc::::::ccccc::::::::cc:::cc::::::cccllloooddxxxkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000
;;,,,,,,,,,'''''''''',,,,,;;;:::ccccccllllccccccccccccllllllllccccc:::::clllllccccccc::::::::::::ccllllooddxxxkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000
;;,,,,''''.................'',,;;;;::ccccccccccccccccclllllllllllccccccclloooolllcc:::::::::::::cccllllodxxkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
;;,,,'''.......................''',,;;:::cccccccccccccllllooooolllcllllooooooolccc:::::;;:::::::ccllloodxkkOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkOOOOOOO
;;,,,''''.........................''',,;;::::::::::::cclllooooooooooooodddollllcc::::::::::::::cccccclloooddxxkkOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkOOOO
;;,,,,''''...'''',,,,,,''''''''''''''',,,;;;;;:::;;:::cclloooooddddddddxddooolcccc::::::::;;;;,,'.........',;::cclooddxxxkkkkxxxxxkkkxxkkkkkkkkkkkkkkk
;;;,,,,,,,,,,;;;::::;;;;;;;;;;;;;;,,,,,,,,,,,;;;;;;;::cclloooodddddxxxxxxdoollcc:::c::;;,,,,;,'...      ...,;;,'',;::cloooddddddxxxxxxxxkkkkkkkkkkkkkk
;;;;;;;;;;;;;::::cc:::::::::::;;;;;;;,,,,,,,,,,,,,;;;::ccloooodddxxxxkkkxdollcc::::::,''',;cc:,....  ..',,,,;;;;;;::ccllooodddddxxxxxxxxxxkkkkkkkkkkOk
;;;;;;;;:::::::ccccccccc::::::;;;;;;,,,,,'''''',,,,;;::ccllooodddxxxkkkkxdolcc::::;,'..',;:clc;'...  .'::;,,;:llloooooooodddddddxxxxxxxxxxxkkkkkkkkOOO
;;;;;;;:::::::ccccccc:cc::::::;;;;;,,,'''''''''',,,;;;:cclooodddxxxxxxxxxdolc:;::;'....',;::ccc;'......',;;:loddxxddddddddddddxxxxxxxxxxxxkkkkkkkkkkOO
;::::::::::::::::::::::::::;;;,,,,,,,''''......'',,,;;:ccllooddxxxxkxxxddolc::::;'........'',,,,''''',;:clodxxxxxxdddddoodddddxxxxxxxxxxxxkkkkkkkkkkkk
;::::::::::::::::::::;;,,'.......................',,;;::ccloodxxxxkkxxddoolcc:::;'.....''''',,,,;;::cloodxxkxxxddddoooooooddddxxxxxxxxxxxxxkkkkkkkkkkk
;:::::::::::;;;;;;,'......            ...........',,;;:cccloddxxxxxxxxdddolccc::;;,,,,,,,;;;;:::cclloodddxxxddooooooooooooddddddxxxxxxxxxxxxxxxxxxxkkk
::::::;;;;;;;,,'..........            .... ......'',;;:ccllodxxxxxxxxxxddollccc::;;;;;;;;;;:::cclllllloooooooooooooooooooooooodddddddddddddddxxxxxxxkk
:::::::;;;;,,'.......,;,'.      ..    ...  ......'',,;:ccllodxxxxxxxxxxddoolllcc:;;;;;;;;;;::::cccccccllllllllllooooooooooooooooooooooooooddddddxxxxxk
:::::::;;;,,'.......',;;,'..         ...........''',,;::cllodxxxxxxxxxxddoooolllcc::::;::::::::::ccccccclllllllllllllllllllllllllllllloooodddddxxxxxxk
:::::::;;;,,'.........''''......................''',,;::cllodxkkkkxxxxxxdddooooolllccc:::::::::::ccccccclllllllllllllllllllllllllllllloooooodddxxxxxxk
::::::::;;;,,,'''''''''''''''....''............'''',,;;:clodxxkkkkkxxxxxxddddddddoooolllcccccccccccclllllllllllllllllllllllllllllllllllloooodddxxxxxxx
:::::::::;;;;;;,,,;,,,;;,,,,,''''''..........''''''',,;:clodxkkkkkkkkkxxxxxxxxxxxddddooooolllllccccllllllllllllllllllllllllllllllllllllooooddddxxxxxxx
::::::::::;;;;;;;;;;;;;;;;;,,,,'''''....''''''',,,,,,,;:clodkOOOkkkkkkkkxxxxxkkxxxxxdddooooolllllllllllllllllllllllllllllllllllllllllloooodddddxxxxxxx
::::::::::::;;;;;;;;;;;,;;;,,,,,,'''''''',,,,,,,,,,,,,;:ccodkOOOOkkkkkkkkkkkkkkkkkxxxxddoooooolllllllllllllllllllllllllllllllllllllllooooodddddxxxxxkk
:::::::::::;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,;;:ccldxOOOOkkOOOOOkkkkkkkkkkkkxxxddooollllllllllllllllllllllllllllllllllllllloooooodddddxxxxxkkk
::::::::::;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,;;::cloxkOOOOOOOOOOOOOOOOOOOkkkxxxddooolllllllllllllllllllllllllllllllllllllllooooooddddxxxxxkkkk
::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,;;;;;;::cloxkkOOOOOOOOOOOOOOOOOOOkkkxxxddoollllllllllllllllllllllllllllllllllllllloooooodddxxxxxxkkkk
::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,;;;;;;::clodxkOO0OOOOO000OOOOOOOOkkkkxxxddooooollllllllllllllllllllllllllllllllllllooooddddxxxkkxkkkk
::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,;;;;;;::ccloxkO00OO0000000OOOOOOOOkkkkkxxdddoooollllllllllllllllllllllllllllllllllloooodddxxxxxxxxkkk
::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;;;;;;;::clodkO0000000000000OOOOOOkkkkkkxxdddoooolllllllllllllllllllllllllllllllllooooddddxxxxxxxxkkk
::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;;;;:cclodxOO0000000000000OOOkkkkkkxxxxdddooolllllllllllllllllllllllllllllllllloooddddxxxxxxxxxkkk
::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cclloxkOO0000000000OOOkkxxxxxxxxxdddooollllllclllllllllllllllllllllllllllloooddddxxxxxxkkkkkk
::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::cllodxkOO00000000OOOkkxxddddddddddooolllccccccclllllllllllllllllllllllllloooddddxxxxxkkkkkkk
::::::::::::::::;;;;;;;;;;;;;::::::::;;;;;;;;,,,,;;;;;;;::clloodxkOOO00000OOOOkkxxxxxdddddddooolllcccccccccllllllllllllllllllllllloooddddxxxxxkkkkkkkk
:::;;;::::::::::;;;;;;;;;;;;::::::::::::;;;;;,,,,;;;;;;;:cclloodxkkOOO0000OOOOkkkkkkkkkkkxxxddoolllcccccccccllllllllllllllllllllllooodddxxxxxkkkkkkkkO
::::::::::::::::;;;;;;;;;;;;::::::::::::::;;;,,,;;;;;;;::ccllloddxkkOO0000OOOkkOOOOO0000OOOkxxdoolllccccccccllllllllllllllllllllllooddddxxxxxkkkkkkkkO
:::::::::::::::::;;;;;;;;;;::::::cccc:c:::;;,,,;;;;;;::::ccclloddxxkOO00000OOOOOO00KKKKKK00OkxdoollllllllcccclllllllllllllllllllllooddddxxxxxkkkkkkkOO
::::::cccc::::::::;;;;;;;;;::::cccccccccc::;;;;::::::::::ccclloddxkkOO000000KKKKKKKKKKKKKK00OkxdoooooooollllllllllllllllllllllllllooddddxxxxxkkkkkkOOO
::::::cccccc:::::::::;;;;;:::::cccccccccc::::::cc::;;::::cclllodxkOO00KKKKKK0OkdoodxkO00000OkxxddddddddoooolllllllllllllllllllllooooddxxxxxxxkkkkkOOOO
:::::::ccccc:::::::::::;;::::::ccccccccccc::::ccllc::;;::cclloodxkO0KKKKK0kxdc;,'',:ldxkOkkkxxdddddxxddddddooolllllllllooooooooooooddxxxxxxkkkkkkOOOOO
::::::::ccccc::::::::::::::::::cccccccccc:::;;:clooolc:::cclooddxkO0KKK0OxdolccccloodxkkkxxxdddddxxxxxxddddddooolllllloooooooooooddddxxxxxkkkkOOOOOOO0
::::::ccccccccc:::::::::::::::ccccccccccc:::;;;:cloolc:::clloddxxkO0KK0kddddxxxkkkkkkxxxdddddddxxxxxxxxxxddddddoooolooooooooodddddddxxxxxkkkOOOOOOOOO0
:::::ccccccccccc:::::::::::::cccccccccc::::::;;;;;::::::::clodxxxkk000OkxxxkkkkkkxxxddddddddddddddddxxxxxxddddddddoooooooooddddddddxxxxxkkkOOOOOOOOO00
:::::cccccccccccc::::::::::::cccccccc::::::::::;;;;;;;;;;::clodxxkkO00OOkkxdddooooooooooooodoooodddddddddddddddddddooooooodddddddxxxxxkkkkkOOOOOOOOOO0
:::::ccccccccccccc:::::::::::::cccccc::::;:::::::::;;;;;;:;;::clooddxxddollllcclllllllllllooooooooddddddxxxxxxxxxxxxddoooodddddxxxxxxkkkkkkOOOO00OOOO0
:::::ccccccccccccccc::::::::::::cccccc:::::::::::::::;;;:::;;;;:::cccc::::::ccccccclllllllllloooodddxxxxxxxxxxxxxxxxxddodddddddxxxxkkkkkkkkOOOO00OOOOO
:::::ccccccccccccccccc::::::::::cccccc:::::::::::::::::;;;;;;:::::::::::::;;;;;:::ccllllllooodddxxxxxxkkkkkkkkkkkkkkxxddddddddxxxxxkkkkkkkkOOOOOOOOOOO
::::cccccccccccccccccc::::::::::ccccccc::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;::cllooddddddddxxxxkkkkkkOOOOOOOOOOkkxxxxddoooddxxxxxxkkkkkkkOOOOOOOOOOO
::::cccccccccccccccccc::::::::::ccccccc::::::::::::::::::::::;;;;;;;;;;::::::cccllooooddddddddddddxxxxxkkkkkkkxdlccclddddooodddxxxxkkkkkkkkOOOOOOOOOO0
:::ccccccccccccccccccc::::::::::cccccccc:::::::::::::::::::::::::::::::::::cccccllllllloooooooooddodddddddddolc;'...;ldddooooddxxxkkkkkkkkkOOOOOOOOO00
:::ccccccccccccccccc:::::::::::cccccccccc::::cccc::::;;;;;;;;;;::::;;:::::::cccccllllllooooooooodddddddddxkxo:'.....;lodoooooddxxxkkkkkkkkkOOOOOO00000
::::cccccccccccccc::::::::ccccccccccccclccc::c:::::;;;;,,,,,,,,;;;;;;;;::::::cccccllloooddddoooddddxxkOOOO00xc'...';coddooooooddxxkkkkkkkkkOOOOOO00000
:::::cccccccccccccccccccccccccccccccccllllccc::::;;;;;;;,,,,,,,,,;;;;;;;::::::cclooooooddxxkkxxxxxk0KXXKK00ko:,',,:codxddoooodddxxkkkkkkOOOOOOOOOO0000
:::::::cccc:::ccccccccccccccccccccccclllllllcc::;,'',;;;;;;,,,,;;;;,;;;;::::::ccloodddddxkO0000OkO0KXNK0kxolc:::::lodxxxddoodddxxxkkkkkOOOOOOOOOOOOO00
;::::::::::::::ccccccccccccccccccclllllllllllcc:;,'.....',;,,,,;;,,,;::::ccc::cclodxOOOkkkOKXXK0OO0XNN0xl:;::clccldxxxxxddddddxxxxkkkkkOOOOOOOOOOOOOOO
;;::::::::::::cccccccccccccccclllllllllllllllccc::,'.....';:;;:::;;:cloodddoolodxxO0KXKOkO0KXNXXK00XXKkl:;:cccllodxkkxxxxdddxxxxxxkkkkkkkkkOOOOOOOOOOO
;;;;::::::::::ccccccccccccccccllllllllllllllllccc::;,'....';ccccllcloxkkkOOOkxxkkO00KXXK0O0KXXNX0xdkkxoc:clllllodxkkkxxxxxxxxxxxxkkkkkkkkkkkOOOOOOOOOO
;;;;;:::::::::cccccccc:::ccccccclllllllllllllllcc:::;;,''..,:clllooodxkkkO000OkkkOO00KXXK00KKXX0x:,;::ccllllllodxkkkkxxxxxxxxxxxxkkkkkkkkkkkOOOOOOOOOO
;;;;;::::::::::cccccc:::::::cccccllllllllllllllccc::::;;,'''';loooodxxkkkO0000OkOOO00XXX0OO00Oko:;,,;:cloolloodxkOOkkxxxxxxxxxxxxkkkkkkkkkkkkOOOOOOOOO
;;;;;;::::::::::::::::::::::ccccccllllllllllllllcccc:::;,,,''';codxxkkkkkO00K0kxkkO000Oxocccc:;,,;::cclllooodxkkOOkkkxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOO
;;;;;;;;;:::::::::::::::::::ccccccccclllllllllllllcccc::;;,,,'',;cloooddxxdddl:::loool:,,,''',,;::ccclllooddxkkOOkkkxxxxxkkkkkkkkkkkkkkkkkkkkOOOOOOOOO
;;;;;;;;;;:::::::::::::::::::cccccclllllllllllllllllccc::;;,,,,,,,,,',,,,,,,''...',,;,,,,,,,;;;:::cclloddddxkOOOkkkxxxxxkkkkkkkkkkkkkkkkkkkkkOOOOOOOOO
;;;;;;;;;;;::::;:::::::::::::cccccclllllllllllllllllcccc::;;,,,,,,'''''''''''.''.'',,;;;;;;;::::ccloooddddxkOOOkkxxxxxxkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOO
;;;;;;;;;;;;;;;;;;:::;;;::::::ccccllllllllllllllllllccccc::;;,,,,,,,,,,,,,,,,,,,,;;;::;:::;;::clloooddddxxkkOkkkxxxxxxkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOO
;;;;;;;;;;;;;;;;;;;;;;;;;:::::ccccllllllllllllllllllcccccc:::;;;,,,,,,,;;;;;;;;;;::::;;;:::::clooddodddxkkOOkkxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOO
;;;;;;;;;;;;;;;;;;;;;;;;;::::::cccclllllllllllllllllccccccc::::;;;,,,,,,;;;;;;;::::::;;:::cclllooooddxxkkkkkkxxxxxxxxkkkkkkkkkkkkkkkkxxxkkkkkkkkOOOOOO
;;;;;;;;;;;;;;;;;;;;;;;::::::::cccccccclllllllllllllllccccccc:::;;;;;;;;;;;;;;::::::::::ccllllllloodxxkkxxxxxxxxxxxxxxkkkkkkkkkkkkkkxxxxxkkkkkkkOOOOOO
EOF